digito = input('Digite algo: ')
print('O tipo primitivo é: ', type(digito))
print('Só tem espaço?', digito.isspace())
print('É um número?', digito.isnumeric())
print('É alfabético?', digito.isalpha())
print('É alfaumérico?', digito.isalnum())
print('Está em maiúsculas?', digito.isupper())
print('Está em minúsculas?', digito.islower())
print('Está capitalizada?', digito.title())
